// Generated by typings
// Source: https://raw.githubusercontent.com/types/npm-path-exists/7de5e21660a8312f2bfbba4e83290eb8297c15e1/index.d.ts
declare module 'path-exists' {
function pathExists(path: string): PromiseLike<boolean>;

namespace pathExists {
  export function sync(path: string): boolean;
}

export = pathExists;
}
